[project]
name = "hexlet-code"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2.6",
    "gunicorn>=21.2",
    "ruff>=0.13.1",
    "whitenoise>=6.7",
]
